pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                  git branch: 'main', 
                  url: 'https://github.com/EkanshJain98/jenkins'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    cd python-app/
                    docker build -t techyboy987/basic-python-app:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push techyboy987/basic-python-app:${BUILD_NUMBER}
                    '''
                }
            }
        }
      
        stage('Update K8S manifest & push to the same Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'dceea876-e1ae-486d-b992-0570a173ebc7', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        sh '''
                        git config --global user.name "${GIT_USERNAME}"
                        git config --global user.password "${GIT_PASSWORD}"
                        cd python-app/
                        cat python-deploy.yaml
                        sed -i "s|techyboy987/basic-python-app:[^[:space:]]*|techyboy987/basic-python-app:${BUILD_NUMBER}|g" python-deploy.yaml
                        cat python-deploy.yaml
                        git add python-deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/EkanshJain98/jenkins.git HEAD:main
                        '''                        
                }
            }
        }
    }
}
}
